# Generated by Django 2.2.5 on 2019-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('maildid', models.EmailField(max_length=254)),
                ('contact', models.TextField()),
                ('lastservice', models.DateField()),
            ],
        ),
    ]
