# Generated by Django 2.2.5 on 2019-09-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190922_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='maildid',
            new_name='mailid',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
    ]
