# Generated by Django 2.2.5 on 2019-09-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190923_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
