# Generated by Django 2.2.5 on 2019-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190926_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='investment',
            field=models.FloatField(default=0),
        ),
    ]
